20.Б10-мм, Волков, 2 дз, 4 задание
Alexander-Volkov-144/spbu_2020_c_homeworks pull request #4
Opened 2020-09-26 12:34 UTC by Alexander-Volkov-144

2020-09-27 06:57 UTC, nbirillo requested changes
За комментарии отдельное спасибо :)

2020-09-27 06:57 UTC, nbirillo commented on homework_2/task_2.4.c
> +    return;
Зачем нужен `return`, если у тебя `void`?

2020-09-27 06:57 UTC, nbirillo commented on homework_2/task_2.4.c
> +    int numbers[10]; // 10 - максимальное количество цифр в числе, которое может быть записано в  int
Можно без таких захардкоженных значений? Заведи константу для этого + сразу нужна инициализация

2020-09-27 06:57 UTC, nbirillo commented on homework_2/task_2.4.c
> +    }
Вынести это в отдельную функцию

2020-09-27 06:57 UTC, nbirillo commented on homework_2/task_2.4.c
> +    }
Ну если используешь сортировку, то:
1. Вынеси ее в отдельную функцию
2. Используй что-то более быстрое, например [быструю сортировку](https://ru.wikipedia.org/wiki/%D0%91%D1%8B%D1%81%D1%82%D1%80%D0%B0%D1%8F_%D1%81%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0)

2020-09-27 06:57 UTC, nbirillo commented on homework_2/task_2.4.c
> +            }
Очень похоже, что ты хотел использовать `while` :) + давай вынесем это в отдельную функцию

2020-09-28 17:10 UTC, nbirillo requested changes

2020-09-28 17:10 UTC, nbirillo commented on homework_2/task_2.4.c
> +    }
Можно инициализировать массив без цикла

2020-09-28 17:10 UTC, nbirillo commented on homework_2/task_2.4.c
> +void zeroMove(int* array)
Видимо `moveFirstZero`? Я думала, что это подвинуть все нули, а оказаолось, что только первый

2020-09-28 17:10 UTC, nbirillo commented on homework_2/task_2.4.c
> +int maxSize = 20; // 20 - максимальное количество цифр в числе, которое может быть записано в  unsigned long long
Это видимо `const`? И правила нэйминга у констант другой :)

2020-09-28 17:10 UTC, nbirillo commented on homework_2/task_2.4.c
> +    scanf("%d", &x);
`%d` для `int`, а у тебя это `unsigned long long`

2020-09-28 17:10 UTC, nbirillo commented
Помечай `Resolve conversatio`n, если исправляешь проблему

2020-09-29 09:58 UTC, nbirillo requested changes
Еще конфликты почини

2020-09-29 09:58 UTC, nbirillo commented on homework_2/task_2.4.c
> +    int numbers[maxSize];
Нельзя оставлять переменную без инициализации :) Ее надо сразу инициаилизировать

2020-09-29 20:09 UTC, Alexander-Volkov-144 commented on homework_2/task_2.4.c
> +    int numbers[maxSize];
Тут нельзя использовать "= { 0 }", видимо из-за использования maxSize вместо какого-то числа. Так что остается только memset, который я и использовал.

2020-09-30 07:17 UTC, nbirillo commented on homework_2/task_2.4.c
> +    int numbers[maxSize];
Как раз можно) Дело в том, что у тебя `maxSize` помечено `const`, это значит, что это неизменяемая переменная и поэтому память будет выделена. А если вот ты уберешь `const`, то будут проблемы

2020-09-30 07:18 UTC, nbirillo commented on homework_2/task_2.4.c
> +    int numbers[maxSize];
И убери заодно еще неиспользуемый заголовок `#include <string.h>`

2020-09-30 08:09 UTC, Alexander-Volkov-144 commented on homework_2/task_2.4.c
> +    int numbers[maxSize];
<img width="766" alt="error" src="https://user-images.githubusercontent.com/70965603/94659663-4e6a9c80-030d-11eb-8c15-a8123f77ac23.png">
Если использовать const int, то не работает, поэтому я сделал через define

2020-09-30 09:10 UTC, nbirillo commented on homework_2/task_2.4.c
> +    int numbers[maxSize];
Это странно, а каким компилятором ты пользуешься? (у меня работает)

2020-09-30 09:12 UTC, nbirillo approved these changes
Зачтено!

2020-09-30 09:12 UTC, merged