20Б.10-мм, Волков, 2 дз, 3 задание
Alexander-Volkov-144/spbu_2020_c_homeworks pull request #5
Opened 2020-09-26 13:15 UTC by Alexander-Volkov-144

2020-09-27 07:04 UTC, nbirillo requested changes

2020-09-27 07:04 UTC, nbirillo commented on homework_2/task_2.3.c
> +#include <malloc.h>
Почему у тебя он? У меня так не работает :) Загугли, что надо подключить, чтоб был виден `malloc` и `free`
![image](https://user-images.githubusercontent.com/8993915/94358244-4c53d400-00a8-11eb-993b-57847860cde6.png)

2020-09-27 07:04 UTC, nbirillo commented on homework_2/task_2.3.c
> +    return;
Зачем `return`, если `void`?

2020-09-27 07:04 UTC, nbirillo commented on homework_2/task_2.3.c
> +int main()
Все в одной функции делать плохо - раздели по функциям, попробуй сам понять, как это лучше сделать (в прошлом PR я написала конкретные места, где это хорошо например). Подели просто на логические части час теперь

2020-09-27 07:04 UTC, nbirillo commented on homework_2/task_2.3.c
> +    }
Можно сделать за линию

2020-09-29 10:01 UTC, nbirillo requested changes
И конфиликты почини

2020-09-29 10:01 UTC, nbirillo commented on homework_2/task_2.3.c
> +void zeroShift(int* array, int n)
Лучше называть функции с глагола, поэтому видимо shiftZeros

2020-09-29 20:14 UTC, Alexander-Volkov-144 commented
Скорее всего мне придется после каждого мерджа менять cmakelist, так как я не знаю, как сделать, чтобы он просто добавлял еще одну строчку туда.

2020-09-30 09:44 UTC, nbirillo approved these changes
Отлично, зачтено!

По поводу конфликтов - да, так и будет. Ну кажется, что поправить конфликты дело пары минут и ты можешь это сделать)

2020-09-30 09:44 UTC, merged