20Б.10-мм, Волков, 2 дз, 2 задание
Alexander-Volkov-144/spbu_2020_c_homeworks pull request #6
Opened 2020-09-26 13:38 UTC by Alexander-Volkov-144

2020-09-27 07:17 UTC, nbirillo requested changes
У меня не запускается - в комменте пример

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +    srand(time(NULL));
Во-первых, так должно быть?

![image](https://user-images.githubusercontent.com/8993915/94358434-ab661880-00a9-11eb-8aad-7a4933048dca.png)

Во-вторых, давай пользователь будет говорить, какое число будет введено (пусть это будет число от 4 до 10 знаков например).
В-третьих, давай без хардкода вида `sec[2] == sec[1] || sec[2] == sec[0]`

Еще добавь проверку на ограничения - то есть, если пользователь введет число 3 или 12 знаков например, то надо попросить ввести его заново

Итог - перепиши весь ввод

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +    int sec[4];
И да, массивы надо инициализировать :) Но тут я подозреваю появится динамический массив, так как пользователь скажет длину.

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +int main()
Опять все внутри `main` - подели на функции

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +    int A = 0, B = 0;
Очень странно именовать не константы капсом

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +    while (A != 4) {
Давай без хардкода + это значние будет вводиться пользователем

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +        scanf("%d", &x);
Соответственно тут тоже будет не обязательно 4значное число + надо будет добавить проверку, что пользовтаель ввел нужное количество цифр в числе

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +        int guess[4];
Переменные надо инициализировать + не будет 4ки

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +        for (int i = 3; i != -1; i--) {
Пожалуйста, без таких захардкоженных значений типа 3
А еще `--i` работает эффективнее в данном случае

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +        B = 0;
Ты же их не менял и они были нулями..........

2020-09-27 07:17 UTC, nbirillo commented on homework_2/task_2.2.c
> +        for (int i = 0; i != 4; ++i) {
Убираем захардкоженную 4ку))) И при обходе массивов проще читать условия вида `i < 4 `

2020-09-28 09:02 UTC, nbirillo requested changes

2020-09-28 09:02 UTC, nbirillo commented on homework_2/task_2.2.c
> +                    b += 1;
Может стоит тогда сделать проверку какую-нибудь? чтобы в одном случае увеличивалось только `b`, а в другом увеличилось только `a`

2020-09-28 17:23 UTC, nbirillo requested changes

2020-09-28 17:23 UTC, nbirillo commented on homework_2/task_2.2.c
> +{
Все еще огрмоный main, который не поделен на функции

2020-09-28 17:23 UTC, nbirillo commented on homework_2/task_2.2.c
> +        printf("A%dB%d\n", a, b);
Можно более читаемый вывод? там даже пробелов нет: A1B2

2020-09-28 17:23 UTC, nbirillo commented on homework_2/task_2.2.c
> +    free(assumptiveNumbers);
Так быть не должно
![image](https://user-images.githubusercontent.com/8993915/94464817-a39c9600-01c7-11eb-8e7d-fd062c2b332e.png)

2020-09-28 17:23 UTC, nbirillo commented on homework_2/task_2.2.c
> +    memset(digits, 0, N * sizeof(bool));
Ну тогда уж значение по умолчанию надо сделать false, раз уж это bool

2020-09-28 19:22 UTC, Alexander-Volkov-144 commented on homework_2/task_2.2.c
> +    free(assumptiveNumbers);
Я проверил корректность использования malloc и free, вроде проблемы быть не должно. В программе функция free используется 3 раза для 3 разных массивов, так что непонятно, почему ide считает, что эта память уже освобождена.

2020-09-29 09:44 UTC, nbirillo requested changes

2020-09-29 09:44 UTC, nbirillo commented on homework_2/task_2.2.c
> +        printf("please enter a %d-digit number\n", n);
![image](https://user-images.githubusercontent.com/8993915/94542098-0e45e400-0251-11eb-9f22-a0fbb3e188c0.png)
У тебя есть проверка, что первая цифра всегда не ноль при генерации - тогда уточни пользователю, что это так. Формально я ввела 4 цифры. После этого можно будет зачесть

2020-09-29 09:44 UTC, nbirillo commented on homework_2/task_2.2.c
> +    free(assumptiveNumbers);
![image](https://user-images.githubusercontent.com/8993915/94542413-709ee480-0251-11eb-9f5c-e73e59f9acb3.png)

2020-09-29 20:29 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-29 20:29 UTC, merged